#pragma once

// Minimal `obsconfig.h` for bindgen.
//
// In OBS builds this header is generated by CMake from `obsconfig.h.in`.
// We only need enough definitions for clang to parse libobs public headers.

#ifndef OBS_DATA_PATH
#define OBS_DATA_PATH "data"
#endif

#ifndef OBS_PLUGIN_PATH
#define OBS_PLUGIN_PATH "plugins"
#endif

#ifndef OBS_PLUGIN_DESTINATION
#define OBS_PLUGIN_DESTINATION ""
#endif

#ifndef OBS_RELEASE_CANDIDATE
#define OBS_RELEASE_CANDIDATE 0
#endif

#ifndef OBS_BETA
#define OBS_BETA 0
#endif

